-- MySQL Script generated by MySQL Workbench
-- 03/03/16 19:33:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dyn_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dyn_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dyn_project` DEFAULT CHARACTER SET utf8 ;
USE `dyn_project` ;

-- -----------------------------------------------------
-- Table `dyn_project`.`Emplacements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`Emplacements` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(45) NULL,
  `Etage` VARCHAR(45) NULL,
  `Password_admin` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`Fournisseurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`Fournisseurs` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Telephone` VARCHAR(45) NULL,
  `Adresse` VARCHAR(255) NULL,
  `TVA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`INV_Ordinateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`INV_Ordinateurs` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Composition` VARCHAR(255) NOT NULL,
  `Marque` VARCHAR(45) NULL,
  `Modele` VARCHAR(45) NULL,
  `Mac_adress` VARCHAR(255) NULL,
  `IP` VARCHAR(255) NULL,
  `FK_Emplacements` INT NULL,
  `Date_achat` DATE NULL,
  `Statut` VARCHAR(45) NULL,
  `FK_Fournisseurs` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Ordi_Emplac_FK_idx` (`FK_Emplacements` ASC),
  INDEX `Ordi_Fourni_FK_idx` (`FK_Fournisseurs` ASC),
  CONSTRAINT `Ordi_Emplac_FK`
    FOREIGN KEY (`FK_Emplacements`)
    REFERENCES `dyn_project`.`Emplacements` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ordi_Fourni_FK`
    FOREIGN KEY (`FK_Fournisseurs`)
    REFERENCES `dyn_project`.`Fournisseurs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`INV_Imprimantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`INV_Imprimantes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Marque` VARCHAR(45) NULL,
  `Modele` VARCHAR(45) NULL,
  `FK_Emplacements` INT NULL,
  `Date_achat` DATE NULL,
  `Statut` VARCHAR(45) NULL,
  `FK_Fournisseurs` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Impri_Emplac_FK_idx` (`FK_Emplacements` ASC),
  INDEX `Impri_Fourni_FK_idx` (`FK_Fournisseurs` ASC),
  CONSTRAINT `Impri_Emplac_FK`
    FOREIGN KEY (`FK_Emplacements`)
    REFERENCES `dyn_project`.`Emplacements` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Impri_Fourni_FK`
    FOREIGN KEY (`FK_Fournisseurs`)
    REFERENCES `dyn_project`.`Fournisseurs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`INV_Consommables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`INV_Consommables` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Marque` VARCHAR(45) NULL,
  `Modele` VARCHAR(45) NULL,
  `FK_Fournisseurs` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Conso_Fourni_FK_idx` (`FK_Fournisseurs` ASC),
  CONSTRAINT `Conso_Fourni_FK`
    FOREIGN KEY (`FK_Fournisseurs`)
    REFERENCES `dyn_project`.`Fournisseurs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`INV_Projecteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`INV_Projecteurs` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Marque` VARCHAR(45) NULL,
  `Modele` VARCHAR(45) NULL,
  `FK_Emplacements` INT NULL,
  `FK_Lampe` INT NULL,
  `Date_achat` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `FK_Fournisseurs` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Proj_Emplac_FK_idx` (`FK_Emplacements` ASC),
  INDEX `Proj_Conso_FK_idx` (`FK_Lampe` ASC),
  INDEX `Proj_Fourni_FK_idx` (`FK_Fournisseurs` ASC),
  CONSTRAINT `Proj_Emplac_FK`
    FOREIGN KEY (`FK_Emplacements`)
    REFERENCES `dyn_project`.`Emplacements` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Proj_Conso_FK`
    FOREIGN KEY (`FK_Lampe`)
    REFERENCES `dyn_project`.`INV_Consommables` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Proj_Fourni_FK`
    FOREIGN KEY (`FK_Fournisseurs`)
    REFERENCES `dyn_project`.`Fournisseurs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`INV_Logiciels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`INV_Logiciels` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Editeur` VARCHAR(45) NULL,
  `Nom` VARCHAR(45) NULL,
  `Version` VARCHAR(45) NULL,
  `Date_activation` DATE NULL,
  `Date_expiration` DATE NULL,
  `Statut_license` VARCHAR(45) NULL,
  `FK_Fournisseurs` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Logi_Fourni_FK_idx` (`FK_Fournisseurs` ASC),
  CONSTRAINT `Logi_Fourni_FK`
    FOREIGN KEY (`FK_Fournisseurs`)
    REFERENCES `dyn_project`.`Fournisseurs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`INV_Impri_Conso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`INV_Impri_Conso` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FK_Imprimantes` INT NULL,
  `FK_Conso` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Impri_FK_idx` (`FK_Imprimantes` ASC),
  INDEX `Conso_FK_idx` (`FK_Conso` ASC),
  CONSTRAINT `Impri_FK`
    FOREIGN KEY (`FK_Imprimantes`)
    REFERENCES `dyn_project`.`INV_Imprimantes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Conso_FK`
    FOREIGN KEY (`FK_Conso`)
    REFERENCES `dyn_project`.`INV_Consommables` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`INV_Logi_Emplac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`INV_Logi_Emplac` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FK_Logiciels` INT NOT NULL,
  `FK_Emplacements` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Logi_FK_idx` (`FK_Logiciels` ASC),
  INDEX `Eplac_FK_idx` (`FK_Emplacements` ASC),
  CONSTRAINT `Logi_FK`
    FOREIGN KEY (`FK_Logiciels`)
    REFERENCES `dyn_project`.`INV_Logiciels` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Eplac_FK`
    FOREIGN KEY (`FK_Emplacements`)
    REFERENCES `dyn_project`.`Emplacements` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`Roles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`Utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`Utilisateurs` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `FK_Roles` INT NULL,
  `Telephone` VARCHAR(45) NULL,
  `LoginGoogle` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `Util_Role_FK_idx` (`FK_Roles` ASC),
  CONSTRAINT `Util_Role_FK`
    FOREIGN KEY (`FK_Roles`)
    REFERENCES `dyn_project`.`Roles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`Statuts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`Statuts` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`Type_materiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`Type_materiel` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`Tickets` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Date` TIMESTAMP NULL,
  `FK_Utilisateurs` INT NULL,
  `Description` LONGTEXT NULL,
  `FK_Statuts` INT NULL,
  `Priorite` VARCHAR(45) NULL,
  `FK_Techniciens` INT NULL,
  `FK_Emplacements` INT NULL,
  `FK_Type_materiel` INT NULL,
  `FK_Materiel_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Tick_Util_FK_idx` (`FK_Utilisateurs` ASC),
  INDEX `Tick_Tech_FK_idx` (`FK_Techniciens` ASC),
  INDEX `Tick_Empla_FK_idx` (`FK_Emplacements` ASC),
  INDEX `Tick_Statut_FK_idx` (`FK_Statuts` ASC),
  INDEX `Tick_Type_mat_FK_idx` (`FK_Type_materiel` ASC),
  CONSTRAINT `Tick_Util_FK`
    FOREIGN KEY (`FK_Utilisateurs`)
    REFERENCES `dyn_project`.`Utilisateurs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tick_Tech_FK`
    FOREIGN KEY (`FK_Techniciens`)
    REFERENCES `dyn_project`.`Utilisateurs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tick_Empla_FK`
    FOREIGN KEY (`FK_Emplacements`)
    REFERENCES `dyn_project`.`Emplacements` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tick_Statut_FK`
    FOREIGN KEY (`FK_Statuts`)
    REFERENCES `dyn_project`.`Statuts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tick_Type_mat_FK`
    FOREIGN KEY (`FK_Type_materiel`)
    REFERENCES `dyn_project`.`Type_materiel` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`ReponsesTickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`ReponsesTickets` (
  `ID` INT NOT NULL,
  `FK_Tickets` INT NULL,
  `Description` LONGTEXT NULL,
  `FK_Utilisateurs` INT NULL,
  `Date` TIMESTAMP NULL,
  PRIMARY KEY (`ID`),
  INDEX `Rep_Tick_FK_idx` (`FK_Tickets` ASC),
  INDEX `Rep_Util_FK_idx` (`FK_Utilisateurs` ASC),
  CONSTRAINT `Rep_Tick_FK`
    FOREIGN KEY (`FK_Tickets`)
    REFERENCES `dyn_project`.`Tickets` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Rep_Util_FK`
    FOREIGN KEY (`FK_Utilisateurs`)
    REFERENCES `dyn_project`.`Utilisateurs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyn_project`.`Contrats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyn_project`.`Contrats` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Date_debut` DATE NULL,
  `Date_fin` DATE NULL,
  `FK_Fournisseurs` INT NULL,
  `FK_Type_materiel` INT NULL,
  `FK_ID_materiel` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Cont_Fourni_FK_idx` (`FK_Fournisseurs` ASC),
  INDEX `Cont_Type_mat_FK_idx` (`FK_Type_materiel` ASC),
  CONSTRAINT `Cont_Fourni_FK`
    FOREIGN KEY (`FK_Fournisseurs`)
    REFERENCES `dyn_project`.`Fournisseurs` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Cont_Type_mat_FK`
    FOREIGN KEY (`FK_Type_materiel`)
    REFERENCES `dyn_project`.`Type_materiel` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
